#!/bin/sh
##### Aliases #####

##### ls, the common ones I use a lot shortened for rapid fire usage
if [[ -n $APPLE && ! -d /usr/local/Cellar/coreutils ]]; then 
    alias ls='ls -G'; 
else
    alias ls='ls --color=auto';
fi
alias l='ls'               # simplest
alias l1='ls -1'           # short,1 column
alias la='ls -A'           # short,show almost all
alias lsa='ls -A'          # short,show almost all
alias lsf='ls -FLsh1'      # single col, show human sizes, append slashes
alias laf='ls -FLAsh1'     # single col, show human sizes, append slashes, almost-all
alias ll='ls -lh'          # long,human readable
alias llb='ls -l'          # long,show all bytes
alias lll='ls -lhL'        # long,human readable, resolve sym links
alias lla='ls -lAph'       # long,show almost all,show type,human readable
alias lrt='ls -tRh'        # short,sorted by date,recursive,show type,human readable
alias llr='ls -lRh'        # long,recursive,show type,human readable
alias lt='ls -lth'         # long,sorted by date,show type,human readable
alias l.='ls -d .[^.]*'    # short,.dotfiles only
alias ll.='ls -ld .[^.]*'  # long,.dotfiles only

##### Screen aliases #####
alias scn='screen'          # start a new screen session
alias scs='screen -S'       # start a new screen session with name $1
alias scl='screen -ls'      # list out screen sessions (default format)
alias scll='sclists'        # list out screen sessions (long format)
alias scr='screen -r'       # resume a screen session
alias scd='screen -d -r'    # detach and resume an attached screen session
alias scc='screen -dm -c'   # start new detached session using the screenrc config file that follows -c

##### tmux aliases #####
alias tm='tmux'
alias tmn='tmux new -s'     # start a new tmux session with name $1
alias tma='tmux attach'     # resume most recent tmux session
alias tmr='tmux attach -t'  # resume a tmux session by name
alias tmll='tmlists long'   # list out tmux sessions (long format)
alias tmls='tmlists'        # list out tmux sessions (default format)

# Session List of screen and tmux
alias sessls='sclists; tmlists long'
alias sls=sessls

##### Ruby/Rails/Rake ##### 
alias rsrv='./script/server -u'
alias rsrvp='ss -p'
alias rcon='./script/console'
alias rmig='rake db:migrate db:test:clone'
alias rdbf='rake db:recreate db:fixtures:load RAILS_ENV=development'
# setup rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

##### Python ##### 
alias  py=python
alias py2=python2
alias py3=python3

##### apache2 #####
alias htc='sudo vim /etc/httpd/conf/httpd.conf'
alias htr='sudo service httpd restart'

##### qsub #####
alias qu='qstat -u $USER'
alias qj="qu -f | grep '[Jj]ob\( Id\|_Name\|_state\)\|resources_used.walltime'"
alias qi='qsub -l walltime=333:33:33,nodes=1:ppn=8 -I -d $PWD'
alias qi2='qsub -l walltime=24:00:00,nodes=1:ppn=8 -I -d $PWD'
alias qi4='qsub -l walltime=48:00:00,nodes=1:ppn=8 -I -d $PWD'
alias qsd='qsub -l walltime=24:00:00,nodes=1:ppn=8 -d $PWD'
alias qs4='qsub -l walltime=48:00:00,nodes=1:ppn=8 -d $PWD'

##### ssh #####
alias ssx='ssh -X'

alias dmesg='sudo dmesg'
alias h='history'
alias vi='vim'

alias grep="grep --color"
alias psx='ps xf -o pid,ppid,pcpu,pmem,vsz,cputime,euser,cmd --sort pid,pcpu --heading --lines=50'
alias psa='ps -A f -o pid,ppid,pcpu,pmem,vsz,cputime,euser,cmd --sort pid,pcpu --heading --lines=50'
alias psc="ps f -o pid,cputime,cmd -C"
alias datey='date +"%Y-%m-%d %H:%M:%S"'
alias treef='tree -FuCh' # /*, user, colors, human sizes
alias duh='du -csh'

# Mac aliases...
if [[ -n $APPLE ]]; then {
  alias top='top -n40 -ocpu -Orsize'
  alias errcode='grep -e"$1" /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Headers/MacErrors.h | more'
  alias macvim='open /Applications/MacVim.app'
  alias psx="ps -x -h -o pid,ppid,pcpu,pmem,vsz,cputime,user,command"
  alias psa="ps -x -h -o pid,ppid,pcpu,pmem,vsz,cputime,user,command -a"
  ##### apache2 #####
  alias htc='sudo vim /etc/apache2/httpd.conf'
  alias htr='sudo /etc/init.d/httpd restart'
}; fi

