#!/bin/bash

# root-specificity for colors
# usage: $(RootColor $root $other)
# default: root = red, other users = yellow
function RootColor {
    rootClr=${1:-$f_Rd}
    dfltClr=${2:-$f_Yl}
    if [[ $UID == 0 ]];
    then echo $rootClr
    else echo $dfltClr
    fi;
}
# short color names for prompt uses
RCy=$(RootColor $f_Rd $f_Yl)
RCw=$(RootColor $f_Rd $f_Wh)

# delimiter color ()-
DC=${f_Gr}
