#!/bin/bash
# ---------------------------------------------------------------------------- #
#                      shell profile of Cometsong rcfiles                      #
#    (This file is sourced by .bashrc and by .zshrc in interactive sessions.)  #
# ---------------------------------------------------------------------------- #

##### load RCPATH env var #####
source $HOME/.rcpath_env

##### Operating Situations #####
case $OSTYPE in
  darwin*)
   export APPLE=TRUE
    ;;
  *)
   export LINUX=TRUE
    ;;
esac

# for tput to complain less
export TERM=xterm

##### multi-dotfile setup #####
source $RCPATH/colors          # load color vars
source $RCPATH/man_colors      # load man_colors
source $RCPATH/aliases         # load aliases
source $RCPATH/sh_functions    # load sh functions

##### Config Vars #####
TZ="America/New_York"
HISTCONTROL=ignoredups:erasedups
export HISTFILE=$(hist_uname)
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
PAGER='less'
HOSTNAME=`uname -n`
EDITOR=vim
umask 002

##### LANGUAGE #####
LANG='en_US.UTF-8'
LC_ALL=$LANG
LC_CTYPE=$LANG

##### Python #####
export PYTHONSTARTUP=$HOME/.pythonrc.py

##### Brews... #####
if [[ -n $APPLE ]]; then
    # for ruby
    PATH="/usr/local/Cellar/ruby/1.9.3-p362/bin:$PATH"
    # for coreutils
    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    # for java
    JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
fi

##### prepend $PATH with $HOME bins
PATH="$HOME/bin:$HOME/.vim/bin:/usr/local/bin:/usr/local/sbin:$PATH"
# parse $PATH, remove duplicate entries, then remove trailing ORS and \n
PATH=$(echo $PATH | awk 'BEGIN{RS=ORS=":"}{ if (a[$0] == 0){ a[$0] += 1; print $0}}' | awk '{sub(/:$/,"");print}' | tr -d '\n')

# if 'my' server-specific rc file exists, source it.
if [[ -e $RCPATH/my_aliases ]]; then source $RCPATH/my_aliases; fi
