#!/bin/bash
# ---------------------------------------------------------------------------- #
#                      shell profile of Cometsong rcfiles                      #
#    (This file is sourced by .bashrc and by .zshrc in interactive sessions.)  #
# ---------------------------------------------------------------------------- #

##### load RCPATH env var #####
source $HOME/.rcpath_env

##### Operating Situations #####
function current_os {
  # If Darwin (OS X)
    if [[ `uname -s` = "Darwin" ]]; then export APPLE=TRUE; fi
  # If Linux (Ubuntu,RedHat,Debian,etc)
    if [[ `uname -s` = "Linux" ]];  then export LINUX=TRUE; fi
  }
# run current_os func here:
current_os

##### multi-dotfile setup ##### 
source $RCPATH/colors          # load color vars
source $RCPATH/aliases         # load aliases 
source $RCPATH/sh_functions    # load sh functions

# if 'my' password-full alias file exists, source it.
if [[ -e $RCPATH/my_aliases ]]; then source $RCPATH/my_aliases; fi

##### Config Vars #####
TZ="Europe/Zurich"
HISTFILE=$HOME/.history
HISTSIZE=2000
SAVEHIST=$HISTSIZE
PAGER='less'
HOSTNAME=`uname -n`
EDITOR=vim
umask 002

##### LANGUAGE #####
LANG='en_US.UTF-8'
LC_ALL=$LANG
LC_CTYPE=$LANG

##### Python #####
export PYTHONSTARTUP=$HOME/.pythonrc.py

##### Brews... #####
if [[ -n $APPLE ]]; then 
    # for ruby
    PATH="/usr/local/Cellar/ruby/1.9.3-p362/bin:$PATH"
    # for python
    PATH="/usr/local/share/python:$PATH"
    PATH="/usr/local/share/python3:$PATH"
    # for coreutils
    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

##### prepend $PATH with $HOME bins
PATH="$HOME/bin:$HOME/.vim/bin:/usr/local/bin:/usr/local/sbin:$PATH"
# parse $PATH, remove duplicate entries, then remove trailing ORS and \n
PATH=$(echo $PATH | awk 'BEGIN{RS=ORS=":"}{ if (a[$0] == 0){ a[$0] += 1; print $0}}' | awk '{sub(/:$/,"");print}' | tr -d '\n')

echo Welcome to ${HOSTNAME} in ${SHELL##*/}!

