#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#                      shell profile of Cometsong rcfiles                      #
#    (This file is sourced by .bashrc and by .zshrc in interactive sessions.)  #
# ---------------------------------------------------------------------------- #

##### load RCPATH env var #####
source ${HOME}/.rcpath_env

##### Operating Situations #####
case $OSTYPE in
  darwin*) export APPLE=TRUE ;;
   linux*) export LINUX=TRUE ;;
        *) export OS_UNK=TRUE ;;
esac

# for tput to complain less
export TERM=xterm

##### multi-dotfile setup #####
if [[ $- == *i* ]]; then 
    source $RCPATH/colors          # load color vars
    source $RCPATH/man_colors      # load man_colors
    source $RCPATH/set_prompt      # configure PWD
fi
source $RCPATH/aliases         # load aliases
source $RCPATH/sh_functions    # load sh functions

##### Config Vars #####
export TZ="America/New_York"
export HISTCONTROL=ignoredups:erasedups:ignorespaces
export HISTFILE=$(hist_uname)
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE
export PAGER='less'
export HOSTNAME=`uname -n`
export EDITOR=vim
umask 002

##### LESS is more #####
if [[ -x $(command -v pygmentize) ]]; then
  export LESS="-SKiRM"
  export LESSOPEN='|pygmentize -f terminal256 -g -P style=stata-dark %s'
else
  export LESS="-SKiM"
fi

##### LANGUAGE #####
export LANG='en_US.UTF-8'
export LC_ALL=$LANG
export LC_CTYPE=$LANG

##### Python #####
export PYTHONSTARTUP=$HOME/.pythonrc.py
export PYTHONUSERBASE=$HOME/local/

##### Brews, etc... #####
if [[ -n $APPLE ]]; then
    # for coreutils
    #PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    #PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
    #MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    # for java
    JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
    # for iTerm2

    # for Go
    GOPATH=~/code/go
    PATH=$PATH:${GOPATH}/bin:/usr/local/opt/go/libexec/bin
fi

##### prepend $PATH with $HOME bins
PATH="$HOME/bin:$HOME/local/bin:$HOME/.vim/bin:/usr/local/bin:/usr/local/sbin:$PATH"
# parse $PATH, remove duplicate entries, then remove trailing ORS and \n
PATH=$(echo $PATH | awk 'BEGIN{RS=ORS=":"}{ if (a[$0] == 0){ a[$0] += 1; print $0}}' | awk '{sub(/:$/,"");print}' | tr -d '\n')

# if 'my' server-specific rc file exists, source it.
if [[ -e $RCPATH/my_aliases ]]; then source $RCPATH/my_aliases; fi
